title: Yash M. Lokare
logo: /assets/img/Yash_Pic.jpg
description: [Google Scholar](https://scholar.google.com/citations?user=eKnJti4AAAAJ&hl=en) and [CV](https://drive.google.com/file/d/110v-q-v8IuD_5_pU4zwfG6FOP3Sj_G0N/view?usp=drive_link)
# show_downloads: true
theme: jekyll-theme-minimal
